@PixelGrid.Server_HostAddress = grpcs://localhost:7232

###

GRPC {{PixelGrid.Server_HostAddress}}/Auth/Register

{
  "userName": "Test",
  "email": "cool@example.com",
  "password": "Password123!"
}


###
